### ISSUE TITLE
Windows app.py error

### ISSUE THREAD

**Issue by SoftologyPro** [HelloVision/HelloMeme#18]
Once installed and trying app.py I get these errors and the script quits.

```
Traceback (most recent call last):
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_multistep.py", line 30, in <module>
    import scipy.stats
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\stats\__init__.py", line 610, in <module>
    from ._stats_py import *
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\stats\_continuous_distns.py", line 12, in <module>
    from scipy.interpolate import BSpline
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\interpolate\__init__.py", line 167, in <module>
    from ._interpolate import *
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\interpolate\_interpolate.py", line 12, in <module>
    from . import _fitpack_py
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\interpolate\_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\scipy\interpolate\_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
TypeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\loaders\single_file.py", line 24, in <module>
    from .single_file_utils import (
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 29, in <module>
    from ..schedulers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.schedulers.scheduling_dpmsolver_multistep because of the following error (look up to see its traceback):


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_img2img.py", line 27, in <module>
    from ...loaders import FromSingleFileMixin, IPAdapterMixin, StableDiffusionLoraLoaderMixin, TextualInversionLoaderMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.single_file because of the following error (look up to see its traceback):
Failed to import diffusers.schedulers.scheduling_dpmsolver_multistep because of the following error (look up to see its traceback):


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Tests\HelloMeme\HelloMeme\app.py", line 9, in <module>
    from hellomeme.utils import (get_drive_pose,
  File "D:\Tests\HelloMeme\HelloMeme\hellomeme\__init__.py", line 11, in <module>
    from .pipelines import HMVideoPipeline, HMImagePipeline
  File "D:\Tests\HelloMeme\HelloMeme\hellomeme\pipelines\__init__.py", line 11, in <module>
    from .pipline_hm_image import HMImagePipeline
  File "D:\Tests\HelloMeme\HelloMeme\hellomeme\pipelines\pipline_hm_image.py", line 22, in <module>
    from diffusers import StableDiffusionImg2ImgPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 844, in __getattr__
    value = getattr(module, name)
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 844, in __getattr__
    value = getattr(module, name)
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_img2img because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.single_file because of the following error (look up to see its traceback):
Failed to import diffusers.schedulers.scheduling_dpmsolver_multistep because of the following error (look up to see its traceback):
```

To make it easy to replicate, here is an install.bat to install

```
@echo off

echo *** %time% *** Deleting HelloMeme directory if it exists
if exist HelloMeme\. rd /S /Q HelloMeme

echo *** %time% *** Cloning HelloMeme repository
git clone https://github.com/HelloVision/HelloMeme
cd HelloMeme

echo *** %time% *** Creating venv
python -m venv venv

echo *** %time% *** Activating venv
call venv\scripts\activate.bat

echo *** %time% *** Installing requirements
python -m pip install --upgrade pip
pip install diffusers==0.31.0
pip install transformers einops scipy opencv-python tqdm pillow onnxruntime onnx safetensors accelerate peft
pip install gradio
pip install imageio[ffmpeg]

echo *** %time% *** Installing GPU torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.4.1+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

call venv\scripts\deactivate.bat
cd ..
echo *** %time% *** Finished HelloMeme install
echo.
echo Check the stats for any errors.  Do not assume it worked.
pause
```

and a run.bat to start app.py.

```
@echo off
cd HelloMeme
call venv\scripts\activate.bat
python app.py
call venv\scripts\deactivate.bat
cd..

```

Save them both into an empty diirectory.  Run install.bat to install then run.bat to run.

**Comment by SoftologyPro** [comment]
OK, I worked it out.  On Windows you need diffusers==0.30.3 to avoid the above error.
That gets past the above error and gets the UI launching.
I pick an image and video and click Generate and get this error

```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\gradio\blocks.py", line 2015, in process_api
    result = await self.call_function(
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\gradio\blocks.py", line 1562, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Tests\HelloMeme\HelloMeme\app.py", line 58, in inference_video
    ref_image = cv2.cvtColor(np.array(ref_image_pil), cv2.COLOR_RGB2BGR)  # Keep as NumPy array
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
```

Then I rolled back opencv-python to 4.9.0.80
That gets past that error and the generation starts, but then shows "Error: Connection errored out."
No stats as to why in the command prompt, just

```
D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
create onnx session cost: 0.029s. D:\code\delphi\Chaos\Examples\MachineLearning\.cache\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_face_landmark.onnx
create onnx session cost: 0.024s. D:\code\delphi\Chaos\Examples\MachineLearning\.cache\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_face_det.onnx
create onnx session cost: 0.033s. D:\code\delphi\Chaos\Examples\MachineLearning\.cache\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_arkit_blendshape.onnx
create onnx session cost: 0.945s. D:\code\delphi\Chaos\Examples\MachineLearning\.cache\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188\hello_3dmm.onnx
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 21.53it/s]
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

D:\Tests\HelloMeme>
```

I really need a tested/working requirements.txt with version numbers that will get this working
https://softologyblog.wordpress.com/2023/10/10/a-plea-to-all-python-developers/

**Comment by SoftologyPro** [comment]
Making sure numpy is the right version helps that last error.

pip uninstall -y numpy
pip uninstall -y numpy
pip install numpy==2.1.3

The UI now launches and I can select an image and video.  The generation seems to work OK, ie
```

DET stage1: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:11<00:00, 21.41it/s]
DET stage2: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:11<00:00, 21.03it/s]
HEAD POSE: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:33<00:00,  7.20it/s]
  0%|                                                                                                                                                                                                                                                | 0/240 [00:00<?, ?it/s]D:\Tests\HelloMeme\HelloMeme\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:540: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
FACE part0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:02<00:00, 108.96it/s]
FACE part1: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:02<00:00, 119.40it/s]
FACE part2: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:02<00:00, 118.08it/s]
ARKIT BS: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:02<00:00, 82.19it/s]
GEN stage1: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [01:06<00:00,  3.61it/s]
GEN stage2: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [04:52<00:00, 11.71s/it]
VAE DECODE: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:09<00:00, 25.82it/s]
```

But then the Gneerated Video shows a blank image and `0:00 / NaN:NaN`
BUT the output_video.mp4 is created and plays outside the UI.  Just that issue showing it in the UI player?

**Comment by songkey** [comment]
Python environment issues can be hard to pinpoint. I have exported a yaml of my local conda environment, which I hope can helping you.

https://github.com/HelloVision/HelloMeme/blob/main/environment.yml

**Comment by SoftologyPro** [comment]
OK, I tweaked my package versions to match yours.  Made everything worse and the UI does not even start.
If anyone gets a working requirements.txt (with versions) for Windows please share.

**Comment by SoftologyPro** [comment]
So, I went back to my previous install and it all works now?!  The output video does show in the UI.
Not sure what changed, but it seems to work as expetced now.

**Comment by SoftologyPro** [comment]
To help any other Windows users get this working, here is an install.bat and run.bat.  Put them both into an empty directory.  Run install.bat to install, then run.bat to start the UI.

install.bat
```
@echo off

echo *** %time% *** Deleting HelloMeme directory if it exists
if exist HelloMeme\. rd /S /Q HelloMeme

echo *** %time% *** Cloning HelloMeme repository
git clone https://github.com/HelloVision/HelloMeme
copy ffmpeg.exe HelloMeme\ffmpeg.exe
copy ffprobe.exe HelloMeme\ffprobe.exe
cd HelloMeme

echo *** %time% *** Creating venv
python -m venv venv

echo *** %time% *** Activating venv
call venv\scripts\activate.bat

echo *** %time% *** Installing requirements
python -m pip install --upgrade pip
pip install transformers einops scipy opencv-python tqdm pillow onnxruntime onnx safetensors accelerate peft
pip install gradio
pip install imageio[ffmpeg]

echo *** %time% *** Installing GPU torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.4.1+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

echo *** %time% *** Installing Diffusers
pip install diffusers==0.30.3

echo *** %time% *** Patching opencv-python
pip uninstall -y opencv-python
pip install opencv-python==4.9.0.80

echo *** %time% *** Patching numpy
pip uninstall -y numpy
pip uninstall -y numpy
pip install numpy==1.26.4

echo *** %time% *** Patching typing_extensions
pip uninstall -y typing_extensions
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts typing_extensions==4.11.0

call venv\scripts\deactivate.bat
cd ..
echo *** %time% *** Finished HelloMeme install
echo.
echo Check the stats for any errors.  Do not assume it worked.
pause
```

run.bat
```
@echo off
cd HelloMeme
call venv\scripts\activate.bat
python app.py
call venv\scripts\deactivate.bat
cd..
```
