### ISSUE TITLE
After run the app, all models will be downloaded

### ISSUE THREAD

**Issue by lior007** [HelloVision/HelloMeme#9]
what models?
What are the file names?
What folder do they go to?

also
Every time I run the APP.PY file
4 files are downloaded to the folder
"C:\Users\LIOR0\.cache\huggingface\hub\models--songkey--hello_group_facemodel\snapshots\a0e34229533a463364929f39ee7e7d72e3d2d188

this is the files:
hello_3dmm.onnx
hello_arkit_blendshape.onnx
hello_face_det.onnx
hello_face_landmark.onnx

Should they stay there?
Or should they be copied to another location?
Why do they go down every time?

**Comment by songkey** [comment]
1. You can find the corresponding file under hellomeme/tools and manually specify the cache directory for the model. For example, you can modify
[`self.deep3d_pred_net = create_onnx_session(hf_hub_download('songkey/hello_group_facemodel', filename='hello_3dmm.onnx'), gpu_id=gpu_id)`](https://github.com/HelloVision/HelloMeme/blob/main/hellomeme/tools/hello_3dmm.py#L40)
 to 
`self.deep3d_pred_net = create_onnx_session(hf_hub_download('songkey/hello_group_facemodel', filename='hello_3dmm.onnx', cache_dir='path/to/you/defined'), gpu_id=gpu_id)`
2. Once a local copy of the model file (.onnx) is available, ` huggingface_hub`  will only verify the file’s integrity on subsequent launches, so it will not re-download the file.

https://huggingface.co/docs/huggingface_hub/guides/download

**Comment by yunyouke** [comment]
How should the downloaded weights be organized? Can you provide a screenshot to show this?

**Comment by zz64** [comment]
>     2. Once a local copy of the model file (.onnx) is available, ` huggingface_hub`  will only verify the file’s integrity on subsequent launches, so it will not re-download the file.

Is there a way to avoid integrity control when there's no internet?


```
Couldn't connect to the Hub: [Errno 101] Network is unreachable.
Will try to load from local cache.
Cannot load model songkey/realisticVisionV60B1_v51VAE: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.
!!! Exception during processing !!! @@ `huggingface-cli login` or using `modelscope`
Traceback (most recent call last):
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpx/_transports/default.py", line 250, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
    raise exc from None
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    raise exc
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 207, in connect_tcp
    with map_exceptions(exc_map):
  File "/home/test/.venvs/py311/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/test/.venvs/py311/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 101] Network is unreachable
``
